"""Add Reservation table

Revision ID: add_reservation_001
Revises: 0763d677d453
Create Date: 2026-06-27 16:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_reservation_001'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('full_name', sa.String(
                        length=120), nullable=False),
                    sa.Column('email', sa.String(length=120), nullable=False),
                    sa.Column('phone', sa.String(length=20), nullable=True),
                    sa.Column('service', sa.String(
                        length=120), nullable=False),
                    sa.Column('reservation_date', sa.String(
                        length=10), nullable=False),
                    sa.Column('reservation_time', sa.String(
                        length=5), nullable=False),
                    sa.Column('message', sa.Text(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    # ### end Alembic commands ###
